services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "${FIBER_PORT}:3000"
      - "${GRPC_PORT}:50051"
      - "${GRPCUI_PORT}:8080"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
