services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - ${FIBER_PORT}:${FIBER_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${GRPCUI_PORT}:${GRPCUI_PORT}
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
