# fly.toml app configuration file generated for page-list-service on 2024-10-23T01:07:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'page-list-service'
primary_region = 'nrt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
  image = 'registry.fly.io/page-list-service:latest'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
