// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: proto/pb/pagelist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{1}
}

type PageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PageList) Reset() {
	*x = PageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageList) ProtoMessage() {}

func (x *PageList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageList.ProtoReflect.Descriptor instead.
func (*PageList) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{2}
}

func (x *PageList) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PageIterator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PageId uint32 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
}

func (x *PageIterator) Reset() {
	*x = PageIterator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageIterator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageIterator) ProtoMessage() {}

func (x *PageIterator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageIterator.ProtoReflect.Descriptor instead.
func (*PageIterator) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{3}
}

func (x *PageIterator) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PageIterator) GetPageId() uint32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageKey string `protobuf:"bytes,1,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPageKey() string {
	if x != nil {
		return x.PageKey
	}
	return ""
}

type BeginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageKey string `protobuf:"bytes,1,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{5}
}

func (x *BeginRequest) GetPageKey() string {
	if x != nil {
		return x.PageKey
	}
	return ""
}

type EndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageKey string `protobuf:"bytes,1,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
}

func (x *EndRequest) Reset() {
	*x = EndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRequest) ProtoMessage() {}

func (x *EndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRequest.ProtoReflect.Descriptor instead.
func (*EndRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{6}
}

func (x *EndRequest) GetPageKey() string {
	if x != nil {
		return x.PageKey
	}
	return ""
}

type NextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IterKey string `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
}

func (x *NextRequest) Reset() {
	*x = NextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRequest) ProtoMessage() {}

func (x *NextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRequest.ProtoReflect.Descriptor instead.
func (*NextRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{7}
}

func (x *NextRequest) GetIterKey() string {
	if x != nil {
		return x.IterKey
	}
	return ""
}

type PrevRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IterKey string `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
}

func (x *PrevRequest) Reset() {
	*x = PrevRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrevRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrevRequest) ProtoMessage() {}

func (x *PrevRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrevRequest.ProtoReflect.Descriptor instead.
func (*PrevRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{8}
}

func (x *PrevRequest) GetIterKey() string {
	if x != nil {
		return x.IterKey
	}
	return ""
}

type InsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IterKey string `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	PageId  uint32 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{9}
}

func (x *InsertRequest) GetIterKey() string {
	if x != nil {
		return x.IterKey
	}
	return ""
}

func (x *InsertRequest) GetPageId() uint32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type EraseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IterKey string `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
}

func (x *EraseRequest) Reset() {
	*x = EraseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseRequest) ProtoMessage() {}

func (x *EraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseRequest.ProtoReflect.Descriptor instead.
func (*EraseRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{10}
}

func (x *EraseRequest) GetIterKey() string {
	if x != nil {
		return x.IterKey
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IterKey string `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	PageId  uint32 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{11}
}

func (x *SetRequest) GetIterKey() string {
	if x != nil {
		return x.IterKey
	}
	return ""
}

func (x *SetRequest) GetPageId() uint32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type PushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListKey string `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	PageId  uint32 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{12}
}

func (x *PushRequest) GetListKey() string {
	if x != nil {
		return x.ListKey
	}
	return ""
}

func (x *PushRequest) GetPageId() uint32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type PopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListKey string `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
}

func (x *PopRequest) Reset() {
	*x = PopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_pagelist_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopRequest) ProtoMessage() {}

func (x *PopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_pagelist_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopRequest.ProtoReflect.Descriptor instead.
func (*PopRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_pagelist_proto_rawDescGZIP(), []int{13}
}

func (x *PopRequest) GetListKey() string {
	if x != nil {
		return x.ListKey
	}
	return ""
}

var File_proto_pb_pagelist_proto protoreflect.FileDescriptor

var file_proto_pb_pagelist_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x1c, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x39, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x2a, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x0c, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x67,
	0x65, 0x4b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x28, 0x0a,
	0x0b, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x69, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x76, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x22, 0x43, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0c, 0x45, 0x72, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0a, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x32,
	0x9c, 0x06, 0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x12, 0x0f, 0x2e, 0x70, 0x61, 0x67,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x70, 0x61,
	0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x12, 0x34, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x61,
	0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x12, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49,
	0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x4e, 0x65, 0x78,
	0x74, 0x12, 0x15, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4e, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x50, 0x72, 0x65, 0x76, 0x12, 0x15, 0x2e, 0x70, 0x61, 0x67,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x05, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x05, 0x45, 0x72, 0x61, 0x73,
	0x65, 0x12, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x72, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x67,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x08, 0x50, 0x75,
	0x73, 0x68, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x15, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07, 0x50, 0x6f, 0x70, 0x42, 0x61,
	0x63, 0x6b, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x50,
	0x75, 0x73, 0x68, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49,
	0x74, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x50, 0x6f, 0x70,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x61,
	0x67, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x46,
	0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x6f, 0x76,
	0x65, 0x53, 0x6e, 0x6f, 0x77, 0x45, 0x78, 0x2f, 0x64, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x32, 0x30,
	0x32, 0x33, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pb_pagelist_proto_rawDescOnce sync.Once
	file_proto_pb_pagelist_proto_rawDescData = file_proto_pb_pagelist_proto_rawDesc
)

func file_proto_pb_pagelist_proto_rawDescGZIP() []byte {
	file_proto_pb_pagelist_proto_rawDescOnce.Do(func() {
		file_proto_pb_pagelist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pb_pagelist_proto_rawDescData)
	})
	return file_proto_pb_pagelist_proto_rawDescData
}

var file_proto_pb_pagelist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_pb_pagelist_proto_goTypes = []interface{}{
	(*Page)(nil),          // 0: pagelist.Page
	(*Empty)(nil),         // 1: pagelist.Empty
	(*PageList)(nil),      // 2: pagelist.PageList
	(*PageIterator)(nil),  // 3: pagelist.PageIterator
	(*DeleteRequest)(nil), // 4: pagelist.DeleteRequest
	(*BeginRequest)(nil),  // 5: pagelist.BeginRequest
	(*EndRequest)(nil),    // 6: pagelist.EndRequest
	(*NextRequest)(nil),   // 7: pagelist.NextRequest
	(*PrevRequest)(nil),   // 8: pagelist.PrevRequest
	(*InsertRequest)(nil), // 9: pagelist.InsertRequest
	(*EraseRequest)(nil),  // 10: pagelist.EraseRequest
	(*SetRequest)(nil),    // 11: pagelist.SetRequest
	(*PushRequest)(nil),   // 12: pagelist.PushRequest
	(*PopRequest)(nil),    // 13: pagelist.PopRequest
}
var file_proto_pb_pagelist_proto_depIdxs = []int32{
	1,  // 0: pagelist.PageListService.New:input_type -> pagelist.Empty
	4,  // 1: pagelist.PageListService.Delete:input_type -> pagelist.DeleteRequest
	5,  // 2: pagelist.PageListService.Begin:input_type -> pagelist.BeginRequest
	6,  // 3: pagelist.PageListService.End:input_type -> pagelist.EndRequest
	7,  // 4: pagelist.PageListService.Next:input_type -> pagelist.NextRequest
	8,  // 5: pagelist.PageListService.Prev:input_type -> pagelist.PrevRequest
	2,  // 6: pagelist.PageListService.Clear:input_type -> pagelist.PageList
	9,  // 7: pagelist.PageListService.Insert:input_type -> pagelist.InsertRequest
	10, // 8: pagelist.PageListService.Erase:input_type -> pagelist.EraseRequest
	11, // 9: pagelist.PageListService.Set:input_type -> pagelist.SetRequest
	12, // 10: pagelist.PageListService.PushBack:input_type -> pagelist.PushRequest
	13, // 11: pagelist.PageListService.PopBack:input_type -> pagelist.PopRequest
	12, // 12: pagelist.PageListService.PushFront:input_type -> pagelist.PushRequest
	13, // 13: pagelist.PageListService.PopFront:input_type -> pagelist.PopRequest
	2,  // 14: pagelist.PageListService.New:output_type -> pagelist.PageList
	1,  // 15: pagelist.PageListService.Delete:output_type -> pagelist.Empty
	3,  // 16: pagelist.PageListService.Begin:output_type -> pagelist.PageIterator
	3,  // 17: pagelist.PageListService.End:output_type -> pagelist.PageIterator
	3,  // 18: pagelist.PageListService.Next:output_type -> pagelist.PageIterator
	3,  // 19: pagelist.PageListService.Prev:output_type -> pagelist.PageIterator
	1,  // 20: pagelist.PageListService.Clear:output_type -> pagelist.Empty
	3,  // 21: pagelist.PageListService.Insert:output_type -> pagelist.PageIterator
	3,  // 22: pagelist.PageListService.Erase:output_type -> pagelist.PageIterator
	3,  // 23: pagelist.PageListService.Set:output_type -> pagelist.PageIterator
	3,  // 24: pagelist.PageListService.PushBack:output_type -> pagelist.PageIterator
	1,  // 25: pagelist.PageListService.PopBack:output_type -> pagelist.Empty
	3,  // 26: pagelist.PageListService.PushFront:output_type -> pagelist.PageIterator
	1,  // 27: pagelist.PageListService.PopFront:output_type -> pagelist.Empty
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pb_pagelist_proto_init() }
func file_proto_pb_pagelist_proto_init() {
	if File_proto_pb_pagelist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pb_pagelist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageIterator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrevRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EraseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_pagelist_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pb_pagelist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pb_pagelist_proto_goTypes,
		DependencyIndexes: file_proto_pb_pagelist_proto_depIdxs,
		MessageInfos:      file_proto_pb_pagelist_proto_msgTypes,
	}.Build()
	File_proto_pb_pagelist_proto = out.File
	file_proto_pb_pagelist_proto_rawDesc = nil
	file_proto_pb_pagelist_proto_goTypes = nil
	file_proto_pb_pagelist_proto_depIdxs = nil
}
