// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pb/pagelist.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Page struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Page) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Page) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PageList struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageList) Reset()         { *m = PageList{} }
func (m *PageList) String() string { return proto.CompactTextString(m) }
func (*PageList) ProtoMessage()    {}
func (*PageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{2}
}

func (m *PageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageList.Unmarshal(m, b)
}
func (m *PageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageList.Marshal(b, m, deterministic)
}
func (m *PageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageList.Merge(m, src)
}
func (m *PageList) XXX_Size() int {
	return xxx_messageInfo_PageList.Size(m)
}
func (m *PageList) XXX_DiscardUnknown() {
	xxx_messageInfo_PageList.DiscardUnknown(m)
}

var xxx_messageInfo_PageList proto.InternalMessageInfo

func (m *PageList) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PageIterator struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PageId               uint32   `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageIterator) Reset()         { *m = PageIterator{} }
func (m *PageIterator) String() string { return proto.CompactTextString(m) }
func (*PageIterator) ProtoMessage()    {}
func (*PageIterator) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{3}
}

func (m *PageIterator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageIterator.Unmarshal(m, b)
}
func (m *PageIterator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageIterator.Marshal(b, m, deterministic)
}
func (m *PageIterator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageIterator.Merge(m, src)
}
func (m *PageIterator) XXX_Size() int {
	return xxx_messageInfo_PageIterator.Size(m)
}
func (m *PageIterator) XXX_DiscardUnknown() {
	xxx_messageInfo_PageIterator.DiscardUnknown(m)
}

var xxx_messageInfo_PageIterator proto.InternalMessageInfo

func (m *PageIterator) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PageIterator) GetPageId() uint32 {
	if m != nil {
		return m.PageId
	}
	return 0
}

type DeleteRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

type BeginRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRequest) Reset()         { *m = BeginRequest{} }
func (m *BeginRequest) String() string { return proto.CompactTextString(m) }
func (*BeginRequest) ProtoMessage()    {}
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{5}
}

func (m *BeginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRequest.Unmarshal(m, b)
}
func (m *BeginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRequest.Marshal(b, m, deterministic)
}
func (m *BeginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRequest.Merge(m, src)
}
func (m *BeginRequest) XXX_Size() int {
	return xxx_messageInfo_BeginRequest.Size(m)
}
func (m *BeginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRequest proto.InternalMessageInfo

func (m *BeginRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

type EndRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndRequest) Reset()         { *m = EndRequest{} }
func (m *EndRequest) String() string { return proto.CompactTextString(m) }
func (*EndRequest) ProtoMessage()    {}
func (*EndRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{6}
}

func (m *EndRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndRequest.Unmarshal(m, b)
}
func (m *EndRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndRequest.Marshal(b, m, deterministic)
}
func (m *EndRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndRequest.Merge(m, src)
}
func (m *EndRequest) XXX_Size() int {
	return xxx_messageInfo_EndRequest.Size(m)
}
func (m *EndRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndRequest proto.InternalMessageInfo

func (m *EndRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

type NextRequest struct {
	IterKey              string   `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextRequest) Reset()         { *m = NextRequest{} }
func (m *NextRequest) String() string { return proto.CompactTextString(m) }
func (*NextRequest) ProtoMessage()    {}
func (*NextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{7}
}

func (m *NextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextRequest.Unmarshal(m, b)
}
func (m *NextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextRequest.Marshal(b, m, deterministic)
}
func (m *NextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextRequest.Merge(m, src)
}
func (m *NextRequest) XXX_Size() int {
	return xxx_messageInfo_NextRequest.Size(m)
}
func (m *NextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NextRequest proto.InternalMessageInfo

func (m *NextRequest) GetIterKey() string {
	if m != nil {
		return m.IterKey
	}
	return ""
}

type PrevRequest struct {
	IterKey              string   `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrevRequest) Reset()         { *m = PrevRequest{} }
func (m *PrevRequest) String() string { return proto.CompactTextString(m) }
func (*PrevRequest) ProtoMessage()    {}
func (*PrevRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{8}
}

func (m *PrevRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrevRequest.Unmarshal(m, b)
}
func (m *PrevRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrevRequest.Marshal(b, m, deterministic)
}
func (m *PrevRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrevRequest.Merge(m, src)
}
func (m *PrevRequest) XXX_Size() int {
	return xxx_messageInfo_PrevRequest.Size(m)
}
func (m *PrevRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrevRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrevRequest proto.InternalMessageInfo

func (m *PrevRequest) GetIterKey() string {
	if m != nil {
		return m.IterKey
	}
	return ""
}

type ClearRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{9}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

type InsertRequest struct {
	IterKey              string   `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	PageId               uint32   `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{10}
}

func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (m *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(m, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetIterKey() string {
	if m != nil {
		return m.IterKey
	}
	return ""
}

func (m *InsertRequest) GetPageId() uint32 {
	if m != nil {
		return m.PageId
	}
	return 0
}

type EraseRequest struct {
	IterKey              string   `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EraseRequest) Reset()         { *m = EraseRequest{} }
func (m *EraseRequest) String() string { return proto.CompactTextString(m) }
func (*EraseRequest) ProtoMessage()    {}
func (*EraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{11}
}

func (m *EraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EraseRequest.Unmarshal(m, b)
}
func (m *EraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EraseRequest.Marshal(b, m, deterministic)
}
func (m *EraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EraseRequest.Merge(m, src)
}
func (m *EraseRequest) XXX_Size() int {
	return xxx_messageInfo_EraseRequest.Size(m)
}
func (m *EraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EraseRequest proto.InternalMessageInfo

func (m *EraseRequest) GetIterKey() string {
	if m != nil {
		return m.IterKey
	}
	return ""
}

type SetRequest struct {
	IterKey              string   `protobuf:"bytes,1,opt,name=iter_key,json=iterKey,proto3" json:"iter_key,omitempty"`
	PageId               uint32   `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{12}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetIterKey() string {
	if m != nil {
		return m.IterKey
	}
	return ""
}

func (m *SetRequest) GetPageId() uint32 {
	if m != nil {
		return m.PageId
	}
	return 0
}

type PushRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	PageId               uint32   `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{13}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

func (m *PushRequest) GetPageId() uint32 {
	if m != nil {
		return m.PageId
	}
	return 0
}

type PopRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopRequest) Reset()         { *m = PopRequest{} }
func (m *PopRequest) String() string { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()    {}
func (*PopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{14}
}

func (m *PopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopRequest.Unmarshal(m, b)
}
func (m *PopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopRequest.Marshal(b, m, deterministic)
}
func (m *PopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopRequest.Merge(m, src)
}
func (m *PopRequest) XXX_Size() int {
	return xxx_messageInfo_PopRequest.Size(m)
}
func (m *PopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopRequest proto.InternalMessageInfo

func (m *PopRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

type CloneRequest struct {
	ListKey              string   `protobuf:"bytes,1,opt,name=list_key,json=listKey,proto3" json:"list_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneRequest) Reset()         { *m = CloneRequest{} }
func (m *CloneRequest) String() string { return proto.CompactTextString(m) }
func (*CloneRequest) ProtoMessage()    {}
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae59f2dbfe03848e, []int{15}
}

func (m *CloneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneRequest.Unmarshal(m, b)
}
func (m *CloneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneRequest.Marshal(b, m, deterministic)
}
func (m *CloneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneRequest.Merge(m, src)
}
func (m *CloneRequest) XXX_Size() int {
	return xxx_messageInfo_CloneRequest.Size(m)
}
func (m *CloneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneRequest proto.InternalMessageInfo

func (m *CloneRequest) GetListKey() string {
	if m != nil {
		return m.ListKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Page)(nil), "pagelist.Page")
	proto.RegisterType((*Empty)(nil), "pagelist.Empty")
	proto.RegisterType((*PageList)(nil), "pagelist.PageList")
	proto.RegisterType((*PageIterator)(nil), "pagelist.PageIterator")
	proto.RegisterType((*DeleteRequest)(nil), "pagelist.DeleteRequest")
	proto.RegisterType((*BeginRequest)(nil), "pagelist.BeginRequest")
	proto.RegisterType((*EndRequest)(nil), "pagelist.EndRequest")
	proto.RegisterType((*NextRequest)(nil), "pagelist.NextRequest")
	proto.RegisterType((*PrevRequest)(nil), "pagelist.PrevRequest")
	proto.RegisterType((*ClearRequest)(nil), "pagelist.ClearRequest")
	proto.RegisterType((*InsertRequest)(nil), "pagelist.InsertRequest")
	proto.RegisterType((*EraseRequest)(nil), "pagelist.EraseRequest")
	proto.RegisterType((*SetRequest)(nil), "pagelist.SetRequest")
	proto.RegisterType((*PushRequest)(nil), "pagelist.PushRequest")
	proto.RegisterType((*PopRequest)(nil), "pagelist.PopRequest")
	proto.RegisterType((*CloneRequest)(nil), "pagelist.CloneRequest")
}

func init() {
	proto.RegisterFile("proto/pb/pagelist.proto", fileDescriptor_ae59f2dbfe03848e)
}

var fileDescriptor_ae59f2dbfe03848e = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdf, 0x6f, 0xda, 0x30,
	0x10, 0xc7, 0x0b, 0x94, 0x5f, 0x57, 0x58, 0x27, 0xab, 0x2b, 0x0c, 0xed, 0xa1, 0xca, 0x4b, 0x61,
	0x1a, 0x30, 0xc1, 0xaa, 0x09, 0xb1, 0x87, 0x0d, 0x0a, 0x12, 0x5a, 0x55, 0x45, 0xf0, 0xb6, 0x97,
	0x2a, 0x24, 0x27, 0xb0, 0x00, 0x3b, 0x73, 0x0c, 0x94, 0xbf, 0x74, 0xff, 0xce, 0xe4, 0xb0, 0x34,
	0x66, 0xa3, 0x59, 0xa6, 0xbd, 0xe5, 0xec, 0xbb, 0xfb, 0xda, 0x5f, 0x7f, 0x4e, 0x81, 0x92, 0x2b,
	0xb8, 0xe4, 0x4d, 0x77, 0xda, 0x74, 0xad, 0x19, 0x2e, 0xa9, 0x27, 0x1b, 0xfe, 0x0a, 0xc9, 0x05,
	0xb1, 0x31, 0x84, 0x53, 0xd3, 0x9a, 0x21, 0x79, 0x01, 0x49, 0xea, 0x94, 0x13, 0x57, 0x89, 0x6a,
	0x71, 0x9c, 0xa4, 0x0e, 0xb9, 0x80, 0xb4, 0xa4, 0x72, 0x89, 0xe5, 0xe4, 0x55, 0xa2, 0x9a, 0x1f,
	0xef, 0x03, 0x52, 0x86, 0xac, 0xcd, 0x99, 0x44, 0x26, 0xcb, 0x29, 0x7f, 0x3d, 0x08, 0x8d, 0x2c,
	0xa4, 0x07, 0x2b, 0x57, 0xee, 0x8c, 0x37, 0x90, 0x53, 0x0d, 0xef, 0xa8, 0x27, 0xc9, 0x4b, 0x48,
	0x2d, 0x70, 0xe7, 0x77, 0xcd, 0x8f, 0xd5, 0xa7, 0xd1, 0x81, 0x82, 0xda, 0x1d, 0x49, 0x14, 0x96,
	0xe4, 0xe2, 0xcf, 0x0c, 0x52, 0x82, 0xac, 0x3a, 0xdc, 0x03, 0x75, 0x7c, 0xe9, 0xe2, 0x38, 0xa3,
	0xc2, 0x91, 0x63, 0xbc, 0x85, 0xe2, 0x2d, 0x2e, 0x51, 0xe2, 0x18, 0xbf, 0xaf, 0xd1, 0x93, 0xe4,
	0x35, 0xe4, 0xd4, 0x15, 0x1e, 0xc2, 0x06, 0x59, 0x15, 0x7f, 0xc5, 0x9d, 0x51, 0x83, 0x42, 0x0f,
	0x67, 0x94, 0xc5, 0x48, 0xbd, 0x06, 0x18, 0x30, 0x27, 0x46, 0x62, 0x15, 0xce, 0xee, 0xf1, 0x51,
	0x6a, 0x99, 0x54, 0xa2, 0xd0, 0x33, 0x55, 0xfc, 0x2b, 0xd3, 0x14, 0xb8, 0x89, 0x91, 0x59, 0x83,
	0x42, 0x7f, 0x89, 0x96, 0x88, 0x21, 0xdf, 0x87, 0xe2, 0x88, 0x79, 0x28, 0x62, 0x1c, 0xe0, 0x79,
	0x0f, 0x6b, 0x50, 0x18, 0x08, 0xcb, 0xc3, 0x18, 0x47, 0xfb, 0x0c, 0x30, 0xc1, 0xff, 0x12, 0xfb,
	0x02, 0x67, 0xe6, 0xda, 0x9b, 0xff, 0xfd, 0x6e, 0xcf, 0xb7, 0xb8, 0x06, 0x30, 0xb9, 0x1b, 0xef,
	0xc1, 0xfb, 0x4b, 0xce, 0x62, 0xb0, 0xd1, 0xfa, 0x91, 0x81, 0xf3, 0x80, 0xd0, 0x09, 0x8a, 0x0d,
	0xb5, 0x91, 0xbc, 0x83, 0xd4, 0x3d, 0x6e, 0xc9, 0x79, 0xe3, 0x69, 0x4e, 0x7c, 0x98, 0x2b, 0x24,
	0x5c, 0x08, 0x4a, 0x8c, 0x13, 0xf2, 0x01, 0x32, 0x7b, 0x12, 0x49, 0x29, 0xdc, 0x3f, 0x60, 0xb3,
	0xf2, 0x7b, 0x27, 0xe3, 0x84, 0x74, 0x20, 0xed, 0x33, 0x49, 0x2e, 0xc3, 0x3d, 0x1d, 0xd2, 0xca,
	0xe5, 0xa1, 0x58, 0x30, 0x23, 0xc6, 0x09, 0xb9, 0x81, 0xd4, 0x80, 0x39, 0xe4, 0x42, 0x6b, 0xfa,
	0x84, 0x6c, 0x44, 0xd9, 0x47, 0x38, 0x55, 0xc4, 0x92, 0x57, 0x61, 0x86, 0x46, 0x70, 0x74, 0xa1,
	0x02, 0x58, 0x2f, 0xd4, 0x80, 0x8e, 0x28, 0x6c, 0x41, 0xda, 0xe7, 0x59, 0xbf, 0xa3, 0x0e, 0xf8,
	0x31, 0x5f, 0xba, 0x90, 0xd9, 0x83, 0xad, 0xbb, 0x79, 0x80, 0x7a, 0x84, 0x60, 0x07, 0xd2, 0x3e,
	0xd0, 0xba, 0xa0, 0x4e, 0x78, 0xb4, 0xa9, 0x13, 0x94, 0xba, 0xa9, 0x21, 0xef, 0x11, 0x65, 0x5d,
	0xc8, 0x29, 0xaa, 0x7b, 0x96, 0xbd, 0x38, 0xf0, 0x27, 0x24, 0x3d, 0xd2, 0x9f, 0xac, 0xc9, 0x5d,
	0xbf, 0x56, 0xd3, 0x0d, 0x11, 0x3f, 0xe6, 0xcf, 0x27, 0xc8, 0xab, 0xe6, 0x43, 0xc1, 0x99, 0xfc,
	0x77, 0xc5, 0x36, 0xe4, 0x4c, 0xee, 0xee, 0x8b, 0x63, 0x4b, 0xde, 0xa8, 0x67, 0xe4, 0x0c, 0x0f,
	0x9f, 0x31, 0x1c, 0xaf, 0xe3, 0x73, 0xd1, 0x1b, 0x7e, 0xbb, 0x9d, 0x51, 0x39, 0x5f, 0x4f, 0x1b,
	0x36, 0x5f, 0x35, 0xef, 0xf8, 0x06, 0x27, 0x8c, 0x6f, 0x07, 0x8f, 0x4d, 0xc7, 0xb6, 0x84, 0x53,
	0x6f, 0xbd, 0x6f, 0xb5, 0xeb, 0x53, 0xcb, 0x5e, 0x20, 0x73, 0xea, 0x94, 0x49, 0x14, 0xac, 0x3e,
	0xe7, 0x2b, 0xdc, 0x72, 0xb1, 0x68, 0x06, 0x7f, 0xaa, 0xae, 0x3b, 0x9d, 0x66, 0xfc, 0xa0, 0xfd,
	0x33, 0x00, 0x00, 0xff, 0xff, 0x27, 0xc5, 0xd4, 0x72, 0xbf, 0x06, 0x00, 0x00,
}
